# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Find-Rule-Permissions
version:      1.3
version_from: lib/File/Find/Rule/Permissions.pm
installdirs:  site
requires:
    Devel::AssertOS::Unix:         1
    File::Find::Rule:              0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
